#Não executa a criação das tabelas automáticamente
#Mostra as consultas sql no log
#Formata as queries sql no log

spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true